CONFIG_LOG=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=4096

# Control Plane
CONFIG_I2C=y

# Data Plane
CONFIG_I2S=y
CONFIG_DMA=y

# DISABLE Audio API (Fixes "No SOURCES" warning)
CONFIG_AUDIO=n
CONFIG_AUDIO_CODEC=n
CONFIG_AUDIO_DMIC=n

CONFIG_NEWLIB_LIBC=y