# Enable Standard Peripherals
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
#Defined in  Kconfig to activate the driver
CONFIG_EPSON_S1V3G340=y
# Increase main stack from default (usually 1024) to 4096 bytes 
CONFIG_MAIN_STACK_SIZE=4096